// GENERATED by tools/glm5_binding_contract.txt's companion step - do not hand-edit.
// Block 0's tensors as the PACK records them: offset/size inside dense.bin (live only when
// ttype == 0, i.e. F32), the two dims, and the ggml type id.  ttype 0 = F32 resident in dense.bin;
// anything else is served natively from the GGUF and must go through the engine's dequant path.
//
// THE TRANSFORMS ARE NOT IN THIS TABLE, they are in the contract: conv_{q,k,v} need
// reshape(d_inner, d_conv).T (see trap 1), and no tensor here may be bound by a nearby key name.
#pragma once
#include <cstdint>

struct GlmBlock0Tensor { const char* name; uint64_t offset; uint64_t bytes;
                         int ne0; int ne1; int ttype; };

static const GlmBlock0Tensor kGlmBlock0[] = {
    { "blk.0.attn_k.weight",      16384,         0,   4096,  8192,  8 },
    { "blk.0.attn_norm.weight",      16384,     16384,   4096,     0,  0 },
    { "blk.0.attn_output.weight",      32768,         0,   8192,  4096,  8 },
    { "blk.0.attn_q.weight",      32768,         0,   4096,  8192,  8 },
    { "blk.0.attn_v.weight",      32768,         0,   4096,  8192,  8 },
    { "blk.0.ffn_down.weight",      32768,         0,  12288,  4096,  8 },
    { "blk.0.ffn_gate.weight",      32768,         0,   4096, 12288,  8 },
    { "blk.0.ffn_norm.weight",      32768,     16384,   4096,     0,  0 },
    { "blk.0.ffn_up.weight",      49152,         0,   4096, 12288,  8 },
    { "blk.0.hc_attn_base.weight",      49152,        96,     24,     0,  0 },
    { "blk.0.hc_attn_fn.weight",      49280,         0,  16384,    24,  8 },
    { "blk.0.hc_attn_scale.weight",      49280,        12,      3,     0,  0 },
    { "blk.0.hc_ffn_base.weight",      49344,        96,     24,     0,  0 },
    { "blk.0.hc_ffn_fn.weight",      49472,         0,  16384,    24,  8 },
    { "blk.0.hc_ffn_scale.weight",      49472,        12,      3,     0,  0 },
    { "blk.0.ssm_a",      49536,       256,     64,     0,  0 },
    { "blk.0.ssm_beta.weight",      49792,         0,   4096,    64,  8 },
    { "blk.0.ssm_conv1d_k.weight",      49792,    131072,      4,  8192,  0 },
    { "blk.0.ssm_conv1d_q.weight",     180864,    131072,      4,  8192,  0 },
    { "blk.0.ssm_conv1d_v.weight",     311936,    131072,      4,  8192,  0 },
    { "blk.0.ssm_dt.bias",     443008,     32768,   8192,     0,  0 },
    { "blk.0.ssm_f_a.weight",     475776,         0,   4096,   128,  8 },
    { "blk.0.ssm_f_b.weight",     475776,         0,    128,  8192,  8 },
    { "blk.0.ssm_g_a.weight",     475776,         0,   4096,   128,  8 },
    { "blk.0.ssm_g_b.weight",     475776,         0,    128,  8192,  8 },
    { "blk.0.ssm_norm.weight",     475776,       512,    128,     0,  0 },
};
static const int kGlmBlock0Count = 26;
